PADDY_VARIETIES = [
    {
        "id": "bpt-5204",
        "name": "BPT 5204",
        "display_name": "BPT 5204 / Samba Mahsuri / Sona Masuri",
        "states": ["AP", "TS", "TN"],
        "duration_days": 145,
        "grain_type": "fine",
        "preferred_seasons": ["kharif", "samba", "late_samba", "thaladi"],
        "notes": "Popular South Indian fine rice; listed by ANGRAU/TNAU sources.",
    },
    {
        "id": "mtu-1010",
        "name": "MTU 1010",
        "display_name": "MTU 1010 / Cottondora Sannalu",
        "states": ["AP", "TS"],
        "duration_days": 125,
        "grain_type": "medium",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Common AP/Telangana variety; often used as a shorter duration option.",
    },
    {
        "id": "mtu-7029",
        "name": "MTU 7029",
        "display_name": "MTU 7029 / Swarna",
        "states": ["AP", "TS"],
        "duration_days": 145,
        "grain_type": "coarse",
        "preferred_seasons": ["kharif"],
        "notes": "Swarna is a major Godavari-zone Kharif variety.",
    },
    {
        "id": "mtu-1121",
        "name": "MTU 1121",
        "display_name": "MTU 1121 / Sri Druthi",
        "states": ["AP", "TS"],
        "duration_days": 125,
        "grain_type": "medium",
        "preferred_seasons": ["rabi"],
        "notes": "ANGRAU variety suitable for AP and Telangana; noted for BPH/blast tolerance.",
    },
    {
        "id": "mtu-1061",
        "name": "MTU 1061",
        "display_name": "MTU 1061",
        "states": ["AP", "TS"],
        "duration_days": 135,
        "grain_type": "medium",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Major ANGRAU variety in AP acreage data.",
    },
    {
        "id": "mtu-1064",
        "name": "MTU 1064",
        "display_name": "MTU 1064",
        "states": ["AP", "TS"],
        "duration_days": 135,
        "grain_type": "medium",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Major ANGRAU variety in AP acreage data.",
    },
    {
        "id": "nlr-34449",
        "name": "NLR 34449",
        "display_name": "NLR 34449",
        "states": ["AP", "TN"],
        "duration_days": 125,
        "grain_type": "fine",
        "preferred_seasons": ["rabi", "samba"],
        "notes": "Nellore-linked variety; appears in AP/TN season-variety lists.",
    },
    {
        "id": "nlr-3238",
        "name": "NLR 3238",
        "display_name": "NLR 3238",
        "states": ["AP"],
        "duration_days": 125,
        "grain_type": "fine",
        "preferred_seasons": ["rabi", "kharif"],
        "notes": "Nellore ARS variety reported as comparable with BPT 5204 and MTU 1010.",
    },
    {
        "id": "nlr-145",
        "name": "NLR 145",
        "display_name": "NLR 145",
        "states": ["AP"],
        "duration_days": 120,
        "grain_type": "fine",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Nellore district specific variety",
    },
    {
        "id": "mtu-1001",
        "name": "MTU 1001",
        "display_name": "MTU 1001 / Vijetha",
        "states": ["AP", "TS"],
        "duration_days": 110,
        "grain_type": "medium",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Short duration AP variety",
    },
    {
        "id": "mtu-7029-sub1",
        "name": "Swarna Sub1",
        "display_name": "Swarna Sub1 / MTU 7029 Sub1",
        "states": ["AP", "TS"],
        "duration_days": 148,
        "grain_type": "coarse",
        "preferred_seasons": ["kharif"],
        "notes": "Flood submergence tolerant up to 14 days",
    },
    {
        "id": "jgl-1798",
        "name": "JGL 1798",
        "display_name": "JGL 1798",
        "states": ["AP"],
        "duration_days": 130,
        "grain_type": "fine",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Popular in AP delta regions",
    },
    {
        "id": "rnr-15048",
        "name": "RNR 15048",
        "display_name": "RNR 15048 / Telangana Sona",
        "states": ["TS", "AP", "TN"],
        "duration_days": 125,
        "grain_type": "fine",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "PJTSAU Telangana Sona; widely adopted and known for low glycemic index rice.",
    },
    {
        "id": "knm-118",
        "name": "KNM 118",
        "display_name": "KNM 118 / Kunaram Sannalu",
        "states": ["TS", "AP"],
        "duration_days": 125,
        "grain_type": "fine",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "Popular PJTSAU Telangana rice variety.",
    },
    {
        "id": "jgl-18047",
        "name": "JGL 18047",
        "display_name": "JGL 18047 / Bathukamma",
        "states": ["TS", "AP"],
        "duration_days": 125,
        "grain_type": "medium",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "PJTSAU rice variety used in Telangana.",
    },
    {
        "id": "wgl-347",
        "name": "WGL 347",
        "display_name": "WGL 347 / Somnath",
        "states": ["TS"],
        "duration_days": 130,
        "grain_type": "medium",
        "preferred_seasons": ["kharif", "rabi"],
        "notes": "PJTSAU rice variety.",
    },
    {
        "id": "adt-36",
        "name": "ADT 36",
        "display_name": "ADT 36",
        "states": ["TN"],
        "duration_days": 110,
        "grain_type": "medium",
        "preferred_seasons": ["kuruvai", "navarai", "sornavari"],
        "notes": "TNAU short-duration rice variety for multiple Tamil Nadu seasons.",
    },
    {
        "id": "adt-43",
        "name": "ADT 43",
        "display_name": "ADT 43",
        "states": ["TN"],
        "duration_days": 110,
        "grain_type": "medium",
        "preferred_seasons": ["kuruvai", "navarai", "sornavari"],
        "notes": "TNAU notes caution against cold-weather planting.",
    },
    {
        "id": "adt-45",
        "name": "ADT(R) 45",
        "display_name": "ADT(R) 45",
        "states": ["TN"],
        "duration_days": 115,
        "grain_type": "medium",
        "preferred_seasons": ["kuruvai", "navarai", "sornavari", "semi_dry"],
        "notes": "TNAU short-duration Tamil Nadu variety.",
    },
    {
        "id": "adt-51",
        "name": "ADT 51",
        "display_name": "ADT 51",
        "states": ["TN"],
        "duration_days": 150,
        "grain_type": "medium",
        "preferred_seasons": ["samba"],
        "notes": "TNAU Samba season variety.",
    },
    {
        "id": "adt-52",
        "name": "ADT 52",
        "display_name": "ADT 52",
        "states": ["TN"],
        "duration_days": 150,
        "grain_type": "medium",
        "preferred_seasons": ["samba"],
        "notes": "TNAU Samba season variety.",
    },
    {
        "id": "cr-1009",
        "name": "CR 1009",
        "display_name": "CR 1009 / Ponmani / Savithri",
        "states": ["TN", "AP"],
        "duration_days": 155,
        "grain_type": "medium",
        "preferred_seasons": ["samba"],
        "notes": "Long-duration Tamil Nadu Samba variety.",
    },
    {
        "id": "cr-1009-sub1",
        "name": "CR 1009 Sub1",
        "display_name": "CR 1009 Sub1",
        "states": ["TN"],
        "duration_days": 155,
        "grain_type": "medium",
        "preferred_seasons": ["samba", "rainfed"],
        "notes": "TNAU-listed flood/submergence tolerant Samba option.",
    },
    {
        "id": "improved-white-ponni",
        "name": "Improved White Ponni",
        "display_name": "Improved White Ponni",
        "states": ["TN"],
        "duration_days": 135,
        "grain_type": "fine",
        "preferred_seasons": ["late_samba", "thaladi", "samba"],
        "notes": "TNAU cautions this variety is susceptible to blast.",
    },
]


PADDY_SEASONS = [
    {"id": "kharif", "name": "Kharif", "months": "Jun-Oct", "states": ["AP", "TS"]},
    {"id": "rabi", "name": "Rabi", "months": "Nov-Apr", "states": ["AP", "TS"]},
    {"id": "kuruvai", "name": "Kuruvai", "months": "Jun-Jul", "states": ["TN"]},
    {"id": "samba", "name": "Samba", "months": "Aug", "states": ["TN"]},
    {"id": "late_samba", "name": "Late Samba", "months": "Sep-Oct", "states": ["TN"]},
    {"id": "thaladi", "name": "Thaladi", "months": "Sep-Oct", "states": ["TN"]},
    {"id": "navarai", "name": "Navarai", "months": "Dec-Jan", "states": ["TN"]},
    {"id": "sornavari", "name": "Sornavari", "months": "Apr-May", "states": ["TN"]},
    {"id": "semi_dry", "name": "Semi-dry / rainfed direct seeded", "months": "Jul-Aug", "states": ["TN"]},
]


DISTRICT_COORDS = {
    "nellore": {"latitude": 14.4426, "longitude": 79.9865, "label": "Nellore"},
    "krishna": {"latitude": 16.6100, "longitude": 80.7214, "label": "Krishna"},
    "guntur": {"latitude": 16.3067, "longitude": 80.4365, "label": "Guntur"},
    "east godavari": {"latitude": 17.0005, "longitude": 81.8040, "label": "East Godavari"},
    "west godavari": {"latitude": 16.9174, "longitude": 81.3399, "label": "West Godavari"},
    "srikakulam": {"latitude": 18.2949, "longitude": 83.8938, "label": "Srikakulam"},
    "vizianagaram": {"latitude": 18.1066, "longitude": 83.3956, "label": "Vizianagaram"},
    "visakhapatnam": {"latitude": 17.6868, "longitude": 83.2185, "label": "Visakhapatnam"},
    "prakasam": {"latitude": 15.3370, "longitude": 79.5570, "label": "Prakasam"},
    "kurnool": {"latitude": 15.8281, "longitude": 78.0373, "label": "Kurnool"},
    "kadapa": {"latitude": 14.4674, "longitude": 78.8241, "label": "Kadapa"},
    "anantapur": {"latitude": 14.6819, "longitude": 77.6006, "label": "Anantapur"},
    "chittoor": {"latitude": 13.2172, "longitude": 79.1003, "label": "Chittoor"},
    "hyderabad": {"latitude": 17.3850, "longitude": 78.4867, "label": "Hyderabad"},
    "warangal": {"latitude": 17.9689, "longitude": 79.5941, "label": "Warangal"},
    "karimnagar": {"latitude": 18.4386, "longitude": 79.1288, "label": "Karimnagar"},
    "nizamabad": {"latitude": 18.6725, "longitude": 78.0941, "label": "Nizamabad"},
    "khammam": {"latitude": 17.2473, "longitude": 80.1514, "label": "Khammam"},
    "medak": {"latitude": 18.0481, "longitude": 78.2615, "label": "Medak"},
    "sangareddy": {"latitude": 17.6234, "longitude": 78.0826, "label": "Sangareddy"},
    "rangareddy": {"latitude": 17.3617, "longitude": 78.4986, "label": "Rangareddy"},
    "thanjavur": {"latitude": 10.7870, "longitude": 79.1378, "label": "Thanjavur"},
    "tiruvarur": {"latitude": 10.7661, "longitude": 79.6340, "label": "Tiruvarur"},
    "nagapattinam": {"latitude": 10.7656, "longitude": 79.8424, "label": "Nagapattinam"},
    "madurai": {"latitude": 9.9252, "longitude": 78.1198, "label": "Madurai"},
}


def get_variety(variety_name: str) -> dict | None:
    normalized = variety_name.strip().lower().replace(" ", "").replace("-", "")
    for variety in PADDY_VARIETIES:
        candidates = [
            variety["id"].replace("-", ""),
            variety["name"].lower().replace(" ", "").replace("-", ""),
            variety["display_name"].lower().replace(" ", "").replace("-", ""),
        ]
        if any(normalized in candidate or candidate in normalized for candidate in candidates):
            return variety
    return None


def get_district_coords(district: str) -> dict:
    return DISTRICT_COORDS.get(district.strip().lower(), DISTRICT_COORDS["nellore"])
